[2025-07-19 02:26:55] INFO [contact.views:16] Contact form POST received ‑ ip=127.0.0.1 ‑ path=/send-message/ ‑ at=2025-07-18T20:56:55+00:00
[2025-07-19 02:26:58] INFO [contact.views:37] Email sent successfully from sss@gmail.com
[2025-07-19 02:27:05] INFO [contact.views:16] Contact form POST received ‑ ip=127.0.0.1 ‑ path=/send-message/ ‑ at=2025-07-18T20:57:05+00:00
[2025-07-19 02:27:05] ERROR [contact.views:43] Invalid contact form: {"email": [{"message": "Enter a valid email address.", "code": "invalid"}]}
[2025-07-19 02:28:00] INFO [contact.views:16] Contact form POST received ‑ ip=127.0.0.1 ‑ path=/send-message/ ‑ at=2025-07-18T20:58:00+00:00
[2025-07-19 02:28:00] ERROR [contact.views:43] Invalid contact form: {"email": [{"message": "Enter a valid email address.", "code": "invalid"}]}
[2025-07-19 02:28:17] INFO [contact.views:16] Contact form POST received ‑ ip=127.0.0.1 ‑ path=/send-message/ ‑ at=2025-07-18T20:58:17+00:00
[2025-07-19 02:28:21] INFO [contact.views:37] Email sent successfully from sss@gmail.com
[2025-07-19 16:52:15] WARNING [django.request:248] Not Found: /favicon.ico
[2025-07-19 16:52:15] WARNING [django.server:213] "GET /favicon.ico HTTP/1.1" 404 3243
[2025-07-19 19:12:58] WARNING [django.request:248] Not Found: /sports/images/pic02.jpg
[2025-07-19 19:12:58] WARNING [django.request:248] Not Found: /sports/images/pic01.jpg
[2025-07-19 19:12:58] WARNING [django.request:248] Not Found: /sports/images/pic03.jpg
[2025-07-19 19:12:58] WARNING [django.request:248] Not Found: /sports/images/pic08.jpg
[2025-07-19 19:12:58] WARNING [django.request:248] Not Found: /sports/images/pic04.jpg
[2025-07-19 19:12:58] WARNING [django.request:248] Not Found: /sports/images/pic09.jpg
[2025-07-19 19:12:58] WARNING [django.server:213] "GET /sports/images/pic02.jpg HTTP/1.1" 404 3384
[2025-07-19 19:12:58] WARNING [django.server:213] "GET /sports/images/pic01.jpg HTTP/1.1" 404 3384
[2025-07-19 19:12:58] WARNING [django.server:213] "GET /sports/images/pic03.jpg HTTP/1.1" 404 3384
[2025-07-19 19:12:58] WARNING [django.server:213] "GET /sports/images/pic08.jpg HTTP/1.1" 404 3384
[2025-07-19 19:12:58] WARNING [django.server:213] "GET /sports/images/pic04.jpg HTTP/1.1" 404 3384
[2025-07-19 19:12:58] WARNING [django.server:213] "GET /sports/images/pic09.jpg HTTP/1.1" 404 3384
[2025-07-19 20:13:55] WARNING [django.request:248] Not Found: /sports/images/pic03.jpg
[2025-07-19 20:13:55] WARNING [django.request:248] Not Found: /sports/images/pic02.jpg
[2025-07-19 20:13:55] WARNING [django.request:248] Not Found: /sports/images/pic04.jpg
[2025-07-19 20:13:55] WARNING [django.server:213] "GET /sports/images/pic03.jpg HTTP/1.1" 404 3384
[2025-07-19 20:13:55] WARNING [django.server:213] "GET /sports/images/pic02.jpg HTTP/1.1" 404 3384
[2025-07-19 20:13:55] WARNING [django.server:213] "GET /sports/images/pic04.jpg HTTP/1.1" 404 3384
[2025-07-19 23:51:25] ERROR [django.request:248] Internal Server Error: /sports/
Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\context.py", line 85, in __getitem__
    raise KeyError(key)
KeyError: 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ~~~~~~~^
        type(current), bit
        ^^^^^^^^^^^^^^^^^^
    ):
    ^
AttributeError: type object 'RequestContext' has no attribute 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ~~~^^^^^
ValueError: invalid literal for int() with base 10: 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NUWAA\PycharmProjects\nuwanga_rajapaksha_v1\sports\views.py", line 14, in sports
    return render(request, 'sports.html', {
        'images_row1': images_row1,
        'images_row2': images_row2,
    })
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\templatetags\static.py", line 112, in url
    path = self.path.resolve(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 739, in resolve
    arg_vals.append(arg.resolve(context))
                    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )  # missing attribute
    ^
django.template.base.VariableDoesNotExist: Failed lookup for key [image] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'images_row1': ['java', 'spring-boot', 'python', 'django', 'fastapi', 'react', 'php', 'android', 'html5', 'css', 'javascript', 'docker'], 'images_row2': ['bootstrap', 'material-ui', 'git', 'jira', 'aws', 'android', 'mysql', 'mongodb', 'postman', 'swagger']}]
[2025-07-19 23:51:25] ERROR [django.server:213] "GET /sports/ HTTP/1.1" 500 251508
[2025-07-19 23:51:27] ERROR [django.request:248] Internal Server Error: /sports/
Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\context.py", line 85, in __getitem__
    raise KeyError(key)
KeyError: 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ~~~~~~~^
        type(current), bit
        ^^^^^^^^^^^^^^^^^^
    ):
    ^
AttributeError: type object 'RequestContext' has no attribute 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ~~~^^^^^
ValueError: invalid literal for int() with base 10: 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NUWAA\PycharmProjects\nuwanga_rajapaksha_v1\sports\views.py", line 14, in sports
    return render(request, 'sports.html', {
        'images_row1': images_row1,
        'images_row2': images_row2,
    })
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\templatetags\static.py", line 112, in url
    path = self.path.resolve(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 739, in resolve
    arg_vals.append(arg.resolve(context))
                    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )  # missing attribute
    ^
django.template.base.VariableDoesNotExist: Failed lookup for key [image] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'images_row1': ['java', 'spring-boot', 'python', 'django', 'fastapi', 'react', 'php', 'android', 'html5', 'css', 'javascript', 'docker'], 'images_row2': ['bootstrap', 'material-ui', 'git', 'jira', 'aws', 'android', 'mysql', 'mongodb', 'postman', 'swagger']}]
[2025-07-19 23:51:27] ERROR [django.server:213] "GET /sports/ HTTP/1.1" 500 251508
[2025-07-19 23:51:38] ERROR [django.request:248] Internal Server Error: /sports/
Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\context.py", line 85, in __getitem__
    raise KeyError(key)
KeyError: 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ~~~~~~~^
        type(current), bit
        ^^^^^^^^^^^^^^^^^^
    ):
    ^
AttributeError: type object 'RequestContext' has no attribute 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ~~~^^^^^
ValueError: invalid literal for int() with base 10: 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NUWAA\PycharmProjects\nuwanga_rajapaksha_v1\sports\views.py", line 14, in sports
    return render(request, 'sports.html', {
        'images_row1': images_row1,
        'images_row2': images_row2,
    })
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\templatetags\static.py", line 112, in url
    path = self.path.resolve(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 739, in resolve
    arg_vals.append(arg.resolve(context))
                    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )  # missing attribute
    ^
django.template.base.VariableDoesNotExist: Failed lookup for key [image] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'images_row1': ['java', 'spring-boot', 'python', 'django', 'fastapi', 'react', 'php', 'android', 'html5', 'css', 'javascript', 'docker'], 'images_row2': ['bootstrap', 'material-ui', 'git', 'jira', 'aws', 'android', 'mysql', 'mongodb', 'postman', 'swagger']}]
[2025-07-19 23:51:38] ERROR [django.server:213] "GET /sports/ HTTP/1.1" 500 251506
[2025-07-19 23:51:39] ERROR [django.request:248] Internal Server Error: /sports/
Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\context.py", line 85, in __getitem__
    raise KeyError(key)
KeyError: 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ~~~~~~~^
        type(current), bit
        ^^^^^^^^^^^^^^^^^^
    ):
    ^
AttributeError: type object 'RequestContext' has no attribute 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ~~~^^^^^
ValueError: invalid literal for int() with base 10: 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\NUWAA\PycharmProjects\nuwanga_rajapaksha_v1\sports\views.py", line 14, in sports
    return render(request, 'sports.html', {
        'images_row1': images_row1,
        'images_row2': images_row2,
    })
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\templatetags\static.py", line 112, in url
    path = self.path.resolve(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 739, in resolve
    arg_vals.append(arg.resolve(context))
                    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\NUWAA\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )  # missing attribute
    ^
django.template.base.VariableDoesNotExist: Failed lookup for key [image] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'images_row1': ['java', 'spring-boot', 'python', 'django', 'fastapi', 'react', 'php', 'android', 'html5', 'css', 'javascript', 'docker'], 'images_row2': ['bootstrap', 'material-ui', 'git', 'jira', 'aws', 'android', 'mysql', 'mongodb', 'postman', 'swagger']}]
[2025-07-19 23:51:39] ERROR [django.server:213] "GET /sports/ HTTP/1.1" 500 251506
